# Generated by Django 4.2.4 on 2023-08-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_rename_image_menuimage_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="bookingId",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="restaurant.booking"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.CharField(default="", max_length=1),
        ),
    ]
