# Generated by Django 4.2.4 on 2023-08-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_feedback_bookingid_alter_feedback_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.PositiveIntegerField(),
        ),
    ]
