# Generated by Django 4.2.4 on 2023-08-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_feedback_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="rating",
        ),
    ]
